enum eStageFlags
{
    STAGE_VERTEX  = 0x1,
    STAGE_PIXEL   = 0x2,
    STAGE_COMPUTE = 0x4,
    STAGE_MESH    = 0x8,
    STAGE_ALL     = STAGE_VERTEX | STAGE_PIXEL | STAGE_COMPUTE | STAGE_MESH
};


enum eTextureFormat
{
    NONE,
    R8_UNORM,
    RG8_SRGB,
    RGBA8_SRGB,
    BGRA8_SRGB,
    R8_UNORM,
    RG8_UNORM,
    RGBAS_UNORM,
    BGRAS_UNORM,
    R16_UNORM,
    RG16_UNORM,
    RGBA16_UNORM,
    R8_UINT,
    RG8_UINT,
    RGBA8_UINT,
    BGRA8_UINT,
    R16_UINT,
    RG16_UINT,
    RGBA16_UINT,
    R16_UINT,
    RG16_UINT,
    RGB32_UINT,
    RGBA32_UINT,
    R16_FLOAT,
    RG16_FLOAT,
    RGBA16_FLOAT,
    R32_FLOAT,
    RG32_FLOAT,
    RGB32_FLOAT,
    RGBA32_FLOAT,
    RGB10A2_UNORM,
    RG11B10_FLOAT,
    D16_UNORM,
    D24_UNORM_S8_UINT,
    D32_FLOAT,
    ASTC_4x4_SRGB,
    ASTC_4x4_UNORM,
    BC7_4x4_SRGB,
    BC7_4x4_UNORM,
};

enum eVkTextureFormat
{
    VK_FORMAT_UNDEFINED, // NONE,

    VK_FORMAT_R8_SRGB,       // R8_UNORM,
    VK_FORMAT_R8G8_SRGB,     // RG8_SRGB,
    VK_FORMAT_R8G8B8A8_SRGB, // RGBA8_SRGB,
    VK_FORMAT_B8G8R8A8_SRGB, // BGRA8_SRGB,

    VK_FORMAT_R8_UNORM,           // R8_UNORM,
    VK_FORMAT_R8G8_UNORM,         // RG8_UNORM,
    VK_FORMAT_R8G8B8A8_UNORM,     // RGBAS_UNORM,
    VK_FORMAT_B8G8R8A8_UNORM,     // BGRAS_UNORM,
    VK_FORMAT_R16_UNORM,          // R16_UNORM,
    VK_FORMAT_R16G16_UNORM,       // RG16_UNORM,
    VK_FORMAT_R16G16B16A16_UNORM, // RGBA16_UNORM,

    VK_FORMAT_R8_UINT,           // R8_UINT,
    VK_FORMAT_R8G8_UINT,         // RG8_UINT,
    VK_FORMAT_R8G8B8A8_UINT,     // RGBA8_UINT,
    VK_FORMAT_B8G8R8A8_UINT,     // BGRA8_UINT,
    VK_FORMAT_R16_UINT,          // R16_UINT,
    VK_FORMAT_R16G16_UINT,       // RG16_UINT,
    VK_FORMAT_R16G16B16A16_UINT, // RGBA16_UINT,
    VK_FORMAT_R32_UINT,          // R16_UINT,
    VK_FORMAT_R32G32_UINT,       // RG16_UINT,
    VK_FORMAT_R32G32B32_UINT,    // RGB32_UINT,
    VK_FORMAT_R32G32B32A32_UINT, // RGBA32_UINT,

    VK_FORMAT_R16_SFLOAT,          // R16_FLOAT,
    VK_FORMAT_R16G16_SFLOAT,       // RG16_FLOAT,
    VK_FORMAT_R16G16B16A16_SFLOAT, // RGBA16_FLOAT,

    VK_FORMAT_R32_SFLOAT,          // R32_FLOAT,
    VK_FORMAT_R32G32_SFLOAT,       // RG32_FLOAT,
    VK_FORMAT_R32G32B32_SFLOAT,    // RGB32_FLOAT,
    VK_FORMAT_R32G32B32A32_SFLOAT, // RGBA32_FLOAT,

    VK_FORMAT_A2R10G10B10_UNORM_PACK32, // RGB10A2_UNORM,
    VK_FORMAT_B10G11R11_UFLOAT_PACK32,  // RG11B10_FLOAT,

    VK_FORMAT_D16_UNORM,         // D16_UNORM,
    VK_FORMAT_D24_UNORM_S8_UINT, // D24_UNORM_S8_UINT,
    VK_FORMAT_D32_SFLOAT,        // D32_FLOAT,

    VK_FORMAT_ASTC_4x4_SRGB_BLOCK,  // ASTC_4x4_SRGB,
    VK_FORMAT_ASTC_4x4_UNORM_BLOCK, // ASTC_4x4_UNORM,

    VK_FORMAT_BC7_SRGB_BLOCK,  // BC7_4x4_SRGB,
    VK_FORMAT_BC7_UNORM_BLOCK, // BC7_4x4_UNORM,
};

eVkTextureFormat gTextureFormatToVkTextureFormatMap[] = {
    VK_FORMAT_UNDEFINED, // NONE,

    VK_FORMAT_R8_SRGB,       // R8_UNORM,
    VK_FORMAT_R8G8_SRGB,     // RG8_SRGB,
    VK_FORMAT_R8G8B8A8_SRGB, // RGBA8_SRGB,
    VK_FORMAT_B8G8R8A8_SRGB, // BGRA8_SRGB,

    VK_FORMAT_R8_UNORM,           // R8_UNORM,
    VK_FORMAT_R8G8_UNORM,         // RG8_UNORM,
    VK_FORMAT_R8G8B8A8_UNORM,     // RGBAS_UNORM,
    VK_FORMAT_B8G8R8A8_UNORM,     // BGRAS_UNORM,
    VK_FORMAT_R16_UNORM,          // R16_UNORM,
    VK_FORMAT_R16G16_UNORM,       // RG16_UNORM,
    VK_FORMAT_R16G16B16A16_UNORM, // RGBA16_UNORM,

    VK_FORMAT_R8_UINT,           // R8_UINT,
    VK_FORMAT_R8G8_UINT,         // RG8_UINT,
    VK_FORMAT_R8G8B8A8_UINT,     // RGBA8_UINT,
    VK_FORMAT_B8G8R8A8_UINT,     // BGRA8_UINT,
    VK_FORMAT_R16_UINT,          // R16_UINT,
    VK_FORMAT_R16G16_UINT,       // RG16_UINT,
    VK_FORMAT_R16G16B16A16_UINT, // RGBA16_UINT,
    VK_FORMAT_R32_UINT,          // R16_UINT,
    VK_FORMAT_R32G32_UINT,       // RG16_UINT,
    VK_FORMAT_R32G32B32_UINT,    // RGB32_UINT,
    VK_FORMAT_R32G32B32A32_UINT, // RGBA32_UINT,

    VK_FORMAT_R16_SFLOAT,          // R16_FLOAT,
    VK_FORMAT_R16G16_SFLOAT,       // RG16_FLOAT,
    VK_FORMAT_R16G16B16A16_SFLOAT, // RGBA16_FLOAT,

    VK_FORMAT_R32_SFLOAT,          // R32_FLOAT,
    VK_FORMAT_R32G32_SFLOAT,       // RG32_FLOAT,
    VK_FORMAT_R32G32B32_SFLOAT,    // RGB32_FLOAT,
    VK_FORMAT_R32G32B32A32_SFLOAT, // RGBA32_FLOAT,

    VK_FORMAT_A2R10G10B10_UNORM_PACK32, // RGB10A2_UNORM,
    VK_FORMAT_B10G11R11_UFLOAT_PACK32,  // RG11B10_FLOAT,

    VK_FORMAT_D16_UNORM,         // D16_UNORM,
    VK_FORMAT_D24_UNORM_S8_UINT, // D24_UNORM_S8_UINT,
    VK_FORMAT_D32_SFLOAT,        // D32_FLOAT,

    VK_FORMAT_ASTC_4x4_SRGB_BLOCK,  // ASTC_4x4_SRGB,
    VK_FORMAT_ASTC_4x4_UNORM_BLOCK, // ASTC_4x4_UNORM,

    VK_FORMAT_BC7_SRGB_BLOCK,  // BC7_4x4_SRGB,
    VK_FORMAT_BC7_UNORM_BLOCK, // BC7_4x4_UNORM,

    // COUNT,
};

CTASSERT(sizeof(gTextureFormatToVkTextureFormatMap) / sizeof(eVkTextureFormat) == (s32)eTextureFormat);

eVkTextureFormat TextureFormatToVkTextureFormat(eTextureFormat format)
{
    ASSERT(gTextureFormatToVkTextureFormatMap[(s32)format] == (s32)format);
    return (eVkFormat)format;
}